---
## https://github.com/SummitRoute/osxlockdown only osx 10.11/El Capitan
## https://github.com/alterstep/dnscrypt-osxclient
## https://github.com/herrbischoff/awesome-osx-command-line
## http://csrc.nist.gov/publications/drafts/800-179/sp800_179_draft.pdf

- set_fact:
    install_archives: /private/var/_install

- file: dest="{{ install_archives }}" mode=0755 state=directory
  become: yes

- name: enforce hibernation and evict Filevault keys from memory instead of traditional sleep to memory
  command: "pmset -a {{ item.k }} {{ item.v }}"
  with_items:
    - { k: destroyfvkeyonstandby, v: 1 }
## https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/pmset.1.html
#    - { k: hibernatemode, v: 25 }      ## makes mac hibernate...

#- name: Reset Accessibility settings
#  command: tccutil reset Accessibility

- osx_defaults: domain=com.apple.alf key=globalstate type=bool value=true state=present
- osx_defaults: domain=com.apple.alf key=loggingenabled type=bool value=true state=present
#- osx_defaults: domain=com.apple.alf key=allowsignedenabled type=bool value=true state=present
#- osx_defaults: domain=com.apple.captive.control key=Active type=bool value=false state=present
#- osx_defaults: domain=com.apple.Safari key=IncludeInternalDebugMenu type=bool value=true state=present
#- osx_defaults: domain=com.apple.Safari key=IncludeDevelopMenu type=bool value=true state=present
#- osx_defaults: domain=NSGlobalDomain key=WebKitDeveloperExtras type=bool value=true state=present
- osx_defaults: domain=NSGlobalDomain key=NSDocumentSaveNewDocumentsToCloud type=bool value=false state=present
- name: screen saver with password
  osx_defaults: domain=com.apple.screensaver key=askForPassword type=int value=1 state=present
- osx_defaults: domain=com.apple.screensaver key=askForPasswordDelay type=int value=300 state=present
- name: Use Plain Text Mode as Default in TextEdit
  osx_defaults: domain=com.apple.TextEdit key=RichText type=int value=0 state=present
- name: Show Hidden Files
  osx_defaults: domain=com.apple.finder key=AppleShowAllFiles type=bool value=true state=present
- name: Show Path Bar
  osx_defaults: domain=com.apple.finder key=ShowPathbar type=bool value=true state=present
- name: Enable Smooth Scrolling
  osx_defaults: domain=NSGlobalDomain key=NSScrollAnimationEnabled type=bool value=false state=present
- name: Finder Save to Disk by Default
  osx_defaults: domain=NSGlobalDomain key=NSDocumentSaveNewDocumentsToCloud type=bool value=false state=present
- name: Disable Creation of Metadata Files on Network Volumes
  osx_defaults: domain=com.apple.desktopservices key=DSDontWriteNetworkStores type=bool value=true state=present
- name: Disable Creation of Metadata Files on USB Volumes
  osx_defaults: domain=com.apple.desktopservices key=DSDontWriteUSBStores type=bool value=true state=present
- name: Check for Software Updates Daily
  osx_defaults: domain=com.apple.SoftwareUpdate key=ScheduleFrequency type=int value=1 state=present

- name: Disable bluetooth
  osx_defaults: domain=/Library/Preferences/com.apple.Bluetooth key=ControllerPowerState type=int value=0 state=present
  when: harden_darwin_bluetoothoff is defined and harden_darwin_bluetoothoff
  register: osx_bluetooth
  notify:
    - kill osx bluetooth

## http://jacobsalmela.com/bash-script-enable-access-assistive-devices-programmatically-os-x-mavericks-10-9-x-simulate-keystrokes/
- stat: path='/Library/Application Support/com.apple.TCC/TCC.db'
  register: tccdb
- name: Allow osascript to command keyboard/mouse
## works on osx but not travis osx
#  command: "sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db \"INSERT or REPLACE INTO access VALUES('kTCCServiceAccessibility','com.apple.RemoteDesktopAgent',1,1,1,NULL)\""
  command: "sqlite3 \"/Library/Application Support/com.apple.TCC/TCC.db\" \"INSERT or REPLACE INTO access VALUES('kTCCServiceAccessibility','com.apple.RemoteDesktopAgent',1,1,1,NULL)\""
  when: tccdb.stat.exists
- debug: msg="WARNING! didn't found /Library/Application\ Support/com.apple.TCC/TCC.db"
  when: not tccdb.stat.exists

- block:
    - name: push bluetooth menu script
      copy: src=osx-bluetooth-menu.scpt dest="{{ ansible_env['HOME'] }}/Desktop/osx-bluetooth-menu.scpt" mode=0644
    - name: add bluetooth to menu bar
      command: "osascript {{ ansible_env['HOME'] }}/Desktop/osx-bluetooth-menu.scpt"
  when: "{{ ansible_env['USER'] }}" != 'root'

- name: disable IPv6 noise
  sysctl: name="{{ item.k }}" value="{{ item.v }}" state=present reload=no
  with_items:
## setting net.inet6.ip6.accept_rtadv failed: sysctl: oid 'net.inet6.ip6.accept_rtadv' is read only
#    - { k: 'net.inet6.ip6.accept_rtadv', v: 0 }
    - { k: 'net.inet6.icmp6.rediraccept', v: 0 }
    - { k: 'net.inet6.icmp6.nodeinfo', v: 0 }
    - { k: 'net.inet6.icmp6.nd6_accept_6to4', v: 0 }

## https://github.com/ansible/ansible-modules-extras/pull/995/files
- name: disable launchd services
  command: "launchctl unload -w {{ item }}"
  with_items: "{{ harden_darwin_launchd_services_unload }}"

- name: download fix-macosx.py to disable search engines 'leak'
  get_url: url=https://fix-macosx.com/fix-macosx.py dest="{{ install_archives }}/fix-macosx.py" mode=0755 sha256sum="b5a07e12269a11341c21f5a1a0951d9b9dbb002681ea1c251a325dc04951b9b3"
## as your user?
#- name: execute fix-macosx.py
#  command: 'python {{ install_archives }}/fix-macosx.py'

- name: download osxparanoia hosts
  get_url: url=https://github.com/l1k/osxparanoia/blob/master/hosts dest="{{ install_archives }}/hosts.osxparanoia" mode=0644 sha256sum="a4ce3fd4ce634ea98bd9a485fcd5c03395b848e77b557cf175f18e80f670b487"

- stat: path={{ install_archives }}/osxlockdown
  register: osxl
- name: git clone osxlockdown
  git:
    repo=https://github.com/SummitRoute/osxlockdown
    dest={{ install_archives }}/osxlockdown
#  when: "{{ ansible_distribution_version | regex_replace('^(\d+)\.(\d+)\.(\d+)$', '\\1.\\2') }}" == '10.11'
  when: ansible_distribution_version.find('10.11') != -1 and not osxl.stat.exists

- stat: path={{ install_archives }}/fsmon
  register: fsmon
- name: git clone fsmon
  git:
    repo=https://github.com/nowsecure/fsmon.git
    dest={{ install_archives }}/fsmon
  when: not fsmon.stat.exists


- stat: path=/opt/local/bin/port
  register: mp
- stat: path=/opt/local/bin/go
  register: mpgo
## FIXME! not installing correct packages: only get gobject-introspection, goffice
- name: macports packages install
  macports: name=go state=present
  async: 3600
  poll: 300
  when: mp.stat.exists and not mpgo.stat.exists
  register: mpgo
- debug: var=mpgo
- stat: path=/private/var/root/osxlockdown.audit
  register: osxlfile
- name: build osxlockdown
  shell: "{{ item.c }} chdir={{ item.d }}"
  with_items:
    - { c: "go get gopkg.in/yaml.v2", d: "{{ install_archives }}/osxlockdown" }
    - { c: "go build osxlockdown", d: "{{ install_archives }}/osxlockdown" }
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin"
    GOROOT: "/opt/local/lib/go"
    GOPATH: "/tmp/gowork"
  become: yes
  when: ansible_distribution_version.find('10.11') != -1 and not osxlfile.stat.exists
  ignore_errors: true
- name: execute osxlockdown - audit mode only
  shell: "./osxlockdown | tee /private/var/root/osxlockdown.audit chdir={{ install_archives }}/osxlockdown"
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin"
    GOROOT: "/opt/local/lib/go"
    GOPATH: "/tmp/gowork"
  become: yes
  register: osxlout
  when: ansible_distribution_version.find('10.11') != -1 and not osxlfile.stat.exists and harden_darwin_osxlockdown == 'audit'
  ignore_errors: true
- debug: var=osxlout.stdout_lines
  when: ansible_distribution_version.find('10.11') != -1 and not osxlfile.stat.exists

- name: download dnscrypt-osxclient
  get_url: url=https://github.com/alterstep/dnscrypt-osxclient/releases/download/1.0.11/dnscrypt-osxclient-1.0.11.dmg dest="{{ install_archives }}/dnscrypt-osxclient-1.0.11.dmg" mode=0644 sha256sum="91610e90474cf788430f820f9a13f59d84449773133ff11df1c5ee58a9dfe82e"
  become: yes
- stat: path="/Applications/DNSCrypt Menubar.app"
  register: dnsc
## https://github.com/MWGriffin/ansible-playbooks/blob/master/install/dmg.yaml
- name: Mount dnscrypt-osxclient image
  command: hdiutil attach dnscrypt-osxclient-1.0.11.dmg chdir="{{ install_archives }}"
  when: not dnsc.stat.exists
- name: Install dnscrypt-osxclient pkg
  command: installer -package /Volumes/dnscrypt-pkg/DNSCrypt.pkg -target /
  become: yes
  when: not dnsc.stat.exists
- name: Unmount dnscrypt-osxclient image
  command: hdiutil detach /Volumes/dnscrypt-pkg
  when: not dnsc.stat.exists

#- name: add certificate to keychain - admin store
#  command: "security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <certificate>"
#- name: add certificate to keychain - user store
#  command: "security add-trusted-cert -r trustRoot -k $HOME/Library/Keychains/System.keychain <certificate>"
#  become: yes
#  become_user: targetuser

## https://objective-see.com/products/ransomwhere.html
- name: download ransomwhere
  get_url: url=https://bitbucket.org/objective-see/deploy/downloads/RansomWhere_1.1.0.zip dest="{{ install_archives }}/RansomWhere_1.1.0.zip" mode=0644 sha256sum="7b18e17abd8fb40d7c25f29f65d64a1f65c758d61c9f67c11d9722d1d7486ea9"
  become: yes
#- command: "RansomWhere.app/Contents/MacOS/RansomWhere -install"
#  become: yes

## https://github.com/iSECPartners/yontma-mac

