---

- block:
    - name: testing | run macos-baseline
      shell: "/usr/local/bin/inspec exec https://github.com/juju4/macos-baseline | tee /var/log/inspec.log"
      ignore_errors: true
      register: inspeclog
    - debug: var=inspeclog.stdout_lines

  when: harden_darwin_testing_inspec

- include: testing-privesc.yml
  when: harden_darwin_testing_privesc

- include: testing-speculative.yml
  when: harden_darwin_testing_speculative
