---

- block:
# base ruby/travis/macos 10.11 = 2.0. inspec requires 2.2+
# macports? brew?
    - name: testing | Ensure recent ruby is present
      homebrew:
        name: ruby
        state: present

    - name: testing | Ensure inspec is present
      gem:
        name: inspec
        state: present

    - name: testing | run macos-baseline
      shell: "inspec exec https://github.com/juju4/macos-baseline | tee /var/log/inspec.log"
      ignore_errors: true
      register: inspeclog
    - debug: var=inspeclog.stdout_lines

  when: harden_darwin_testing_inspec
