---
- name: restart sshd
  service: name={{ ssh_svc }} state=restarted
- name: reload fstab
  shell: "umount -a; mount -a"
  ignore_errors: true

- name: kill osx bluetooth
  command: "killall -HUP blued"
  ignore_errors: true

